update

diff --git a/.github/workflows/core-plugins-build-and-release.yml b/.github/workflows/core-plugins-build-and-release.yml
--- a/.github/workflows/core-plugins-build-and-release.yml
+++ b/.github/workflows/core-plugins-build-and-release.yml
@@ -13,12 +13,9 @@ concurrency:
   cancel-in-progress: true
 
 env:
-  NODEJS_VERSION: 18.x
-  GO_VERSION: 1.21
-  GO_LINT_VERSION: 1.51.1
   GRABPL_VERSION: 3.0.44
-  GCP_BUCKET: plugins-community-staging # integration-artifacts
-  GCOM_API: https://grafana-dev.com # https://grafana.com
+  GCP_BUCKET: plugins-community-staging # integration-artifacts # Dev: plugins-community-staging
+  GCOM_API: https://grafana-dev.com # Dev: https://grafana-dev.com
 
 jobs:
   build-and-publish:
@@ -43,14 +40,13 @@ jobs:
       - name: Setup nodejs environment
         uses: actions/setup-node@v3
         with:
-          node-version: ${{ env.NODEJS_VERSION }}
+          node-version-file: .nvmrc
           cache: yarn
       - name: Find plugin directory
         shell: bash
         id: get_dir
         run: |
           dir=$(find public/app/plugins -name ${{ inputs.plugin_id }} -print -quit)
-          echo "Got dir $dir"
           echo "dir=${dir}" >> $GITHUB_OUTPUT
       - name: Install frontend dependencies
         shell: bash
@@ -77,7 +73,7 @@ jobs:
         uses: actions/setup-go@v4
         if: steps.check_backend.outputs.has_backend == 'true'
         with:
-          go-version: ${{ env.GO_VERSION }}
+          go-version-file: go.mod
       - name: Install Mage
         shell: bash
         if: steps.check_backend.outputs.has_backend == 'true'
@@ -154,16 +150,14 @@ jobs:
           api_res=$(curl -X 'GET' -H "Authorization: Bearer $GCOM_TOKEN" \
             '${{ env.GCOM_API}}/api/plugins/${{ inputs.plugin_id }}?version=$VERSION' \
             -H 'accept: application/json')
-          echo $api_res
-          # TODO: Re-enable
-          # api_res_code=$(echo $api_res | jq -r .code)
-          # if [ "$api_res_code" = "NotFound" ]; then
-          #   echo "No existing release found"
-          # else
-          #   echo "Expecting a missing release, got:"
-          #   echo $api_res
-          #   exit 1
-          # fi
+          api_res_code=$(echo $api_res | jq -r .code)
+          if [ "$api_res_code" = "NotFound" ]; then
+            echo "No existing release found"
+          else
+            echo "Expecting a missing release, got:"
+            echo $api_res
+            exit 1
+          fi
       - name: store build artifacts
         uses: actions/upload-artifact@v3
         with:
@@ -217,8 +211,8 @@ jobs:
               }
             }
           }"`
-          echo $result
           if [[ "$(echo $result | jq -r .version)" == "null" ]]; then
-            echo "Failed to publish plugin version"
+            echo "Failed to publish plugin version. Got:"
+            echo $result
             exit 1
           fi
